version: '3'

tasks:
  build:
    desc: "Build plugin + CLI, install CLI binary"
    cmds:
      - cargo build --release --target wasm32-wasip1
      - cd cli && cargo build --release
      - cp cli/target/release/znotify ~/.local/bin/znotify
      - echo "✅ Built and installed znotify CLI"

  install:
    desc: "Install plugin and reload in Zellij"
    deps: [build]
    cmds:
      - cp target/wasm32-wasip1/release/zellij_notify.wasm ~/.config/zellij/plugins/zellij-notify.wasm
      - LOG_FILE=$(find /tmp /var/folders -path "*/zellij-*/zellij-log/zellij.log" 2>/dev/null | head -1) && > "$LOG_FILE"
      - zellij action start-or-reload-plugin file:~/.config/zellij/plugins/zellij-notify.wasm
      - echo "✅ Installed and reloaded"

  setup-claude-hooks:
    desc: "Add Claude Code hooks to settings"
    cmds:
      - ./scripts/setup-claude-hooks.sh

  run:
    desc: "Run znotify CLI without install (like go run)"
    cmds:
      - cargo run --manifest-path cli/Cargo.toml -- {{.CLI_ARGS}}

  logs:
    desc: "View Zellij plugin logs"
    cmds:
      - |
        echo "🔍 Finding Zellij log file..."
        LOG_FILE=$(find /tmp /var/folders -path "*/zellij-*/zellij-log/zellij.log" 2>/dev/null | head -1)

        if [ -z "$LOG_FILE" ]; then
          echo "❌ No log file found. Make sure Zellij is running."
          exit 1
        fi

        echo "📜 Log file: $LOG_FILE"
        echo "========================================"
        echo "Last 100 lines (filtered for zellij-notify):"
        echo "========================================"
        tail -100 "$LOG_FILE" | grep "\[zellij-notify\]" || echo "No [zellij-notify] logs found"
        echo ""
        echo "========================================"
        echo "Tailing logs (Ctrl+C to stop)..."
        echo "========================================"
        tail -f "$LOG_FILE" | grep --line-buffered "\[zellij-notify\]"
